id: smart.who.int.ig-empty
canonical: http://smart.who.int/ig-empty
name: LabTest
title: Laboratory Test IG 
description: A starting point for building IGs
status: draft # draft | active | retired | unknown
experimental: false
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
#fhirVersion: 4.3.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC-BY-SA-3.0-IGO # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#716 "Zimbabwe" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: MOH Zimbabwe
  url: http://mohcc.org.zw
  # email: test@example.org



meta:
  profile:
    - http://smart.who.int/base/StructureDefinition/SGImplementationGuide

pages:
  index.md:
    title: Home


menu:
  Home: 
    Summary: index.html
  